name: Sync with SVN on release
on:
  release:
    types:
      - created
jobs:
  svn_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync with SVN on release
        run: |
          RELEASE_VERSION=`grep "^Stable tag:" readme.txt | awk -F' ' '{print $NF}'`
          echo "version: $RELEASE_VERSION"
          mkdir ~/tmp
          cd ~/tmp
          svn co https://plugins.svn.wordpress.org/wc-buckaroo-bpe-gateway/ --username "${{ secrets.SVN_REP_USER }}" --password "${{ secrets.SVN_REP_PW }}"
          cd wc-buckaroo-bpe-gateway
          svn delete trunk/*
          rsync -r --exclude='.git' --exclude='.github' ${{ github.workspace }}/ trunk/
          svn add trunk/*
          svn commit --username "${{ secrets.SVN_REP_USER }}" --password "${{ secrets.SVN_REP_PW }}" -m "release $RELEASE_VERSION" .
          svn copy --username "${{ secrets.SVN_REP_USER }}" --password "${{ secrets.SVN_REP_PW }}" https://plugins.svn.wordpress.org/wc-buckaroo-bpe-gateway/trunk https://plugins.svn.wordpress.org/wc-buckaroo-bpe-gateway/tags/$RELEASE_VERSION -m "release $RELEASE_VERSION"

